# Generated by Django 5.1.2 on 2024-10-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.TextField(choices=[('ap', 'apple'), ('sm', 'samsung'), ('on', 'oneplus')])),
                ('specs', models.TextField()),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
