# Generated by Django 5.1.2 on 2024-10-23 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.TextField(choices=[('ap', 'apple'), ('sm', 'samsung'), ('on', 'oneplus'), ('v', 'vivo'), ('n', 'nothing')]),
        ),
    ]
