# Generated by Django 5.1.2 on 2024-10-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_mobile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='upload_image',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
