# Generated by Django 5.1.2 on 2024-11-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('dl', 'Delhi'), ('mp', 'Madhya Pradesh'), ('ml', 'Maldives'), ('bn', 'Bankok'), ('cp', 'Canaught Place ')], max_length=100),
        ),
    ]
