# Generated by Django 5.1.2 on 2024-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_customer_locality_alter_customer_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laptops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('category', models.TextField(choices=[('ap', 'apple'), ('sm', 'samsung'), ('on', 'oneplus'), ('v', 'vivo'), ('n', 'nothing')])),
                ('specs', models.TextField()),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
    ]
