# Generated by Django 5.1.2 on 2024-12-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_laptops'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('monitorcategory', models.TextField(choices=[('sm', 'Samsung'), ('ac', 'Accer'), ('ms', 'MSI'), ('ap', 'Apple'), ('gb', 'Gigabyte')])),
                ('specs', models.TextField()),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
        migrations.DeleteModel(
            name='Laptops',
        ),
    ]
