# Generated by Django 5.1.2 on 2024-12-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_monitor_monitorcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='category',
            field=models.TextField(choices=[('ap', 'apple'), ('sm', 'samsung'), ('on', 'oneplus'), ('v', 'vivo'), ('n', 'nothing'), ('la', 'lava'), ('op', 'oppo')]),
        ),
    ]
