# Generated by Django 5.1.2 on 2024-12-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_mobile_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earphones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('monitorcategory', models.TextField(choices=[('sm', 'Samsung'), ('rm', 'Realme'), ('tr', 'truke'), ('bt', 'Boat'), ('mv', 'Mivi'), ('ap', 'Apple')])),
                ('specs', models.TextField()),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
    ]
