# Generated by Django 5.1.2 on 2024-12-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_earphones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earphones',
            old_name='monitorcategory',
            new_name='earphonescategory',
        ),
    ]
