# Generated by Django 5.1.2 on 2024-12-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_earphones_earphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earphone',
            name='earphonescategory',
            field=models.TextField(choices=[('sm', 'Samsung'), ('rm', 'Realme'), ('tr', 'truke'), ('bt', 'Boat'), ('mv', 'Mivi'), ('ap', 'Apple'), ('ns', 'Noise'), ('blt', 'Bolt')]),
        ),
    ]
