# Generated by Django 5.1.2 on 2024-12-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_earphone_earphonescategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamingConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('company', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('earphonescategory', models.TextField(choices=[('ps3', 'Playstation3'), ('ps4', 'Playstation4'), ('xb', 'Xbox360'), ('xb', 'XboxSeriesX'), ('as', 'Asus_Rog_ally')])),
                ('specs', models.TextField()),
                ('description', models.TextField()),
                ('upload_image', models.ImageField(default='', upload_to='product/')),
            ],
        ),
    ]
