# Generated by Django 5.1.2 on 2024-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_gamingconsole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamingconsole',
            name='earphonescategory',
            field=models.TextField(choices=[('ps3', 'Playstation3'), ('ps4', 'Playstation4'), ('ps5', 'Playstation5'), ('xb', 'Xbox360'), ('xb', 'XboxSeriesX'), ('as', 'Asus_Rog_ally')]),
        ),
    ]
