# Generated by Django 5.1.2 on 2025-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_gamingconsole_earphonescategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Company', models.TextField()),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('description', models.TextField()),
              
            ],
        ),
    ]
