# Generated by Django 5.1.2 on 2025-01-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='upload_image',
            field=models.ImageField(default='', upload_to='product/'),
        ),
    ]
