# Generated by Django 5.1.2 on 2025-01-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_games_upload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='gamecategory',
            field=models.TextField(choices=[('GodOfWar', 'GofOfWar'), ('AlanWake', 'AlanWake'), ('WatchDogs2', 'WatchDogs2'), ('RDR2', 'RDR2'), ('GTA 5', 'GTA5'), ('GTA 6', 'GTA6'), ('BlackMythwukon', 'Blckmythwukong')], default=''),
        ),
    ]
